window.BANKSO_PRODUCTS = [
 {id:'maroc',name:'MAROC',country:'MOROCCO',image:'images/back-morocco.jpg',number:'01',description:'Une pièce inspirée des motifs, des textures et de l’identité visuelle du Maroc.',detail:'Une silhouette pensée pour porter la culture avec une esthétique contemporaine.',sizes:['XS','S','M','L','XL','XXL']},
 {id:'japon',name:'JAPON',country:'JAPAN',image:'images/back-japan.jpg',number:'02',description:'Une pièce inspirée de l’esthétique japonaise, entre minimalisme et contraste.',detail:'Une interprétation graphique de l’équilibre entre tradition et modernité.',sizes:['XS','S','M','L','XL','XXL']},
 {id:'italie',name:'ITALIE',country:'ITALY',image:'images/back-italy.jpg',number:'03',description:'Une pièce inspirée du style italien et de son identité visuelle.',detail:'Une ligne sobre et affirmée pensée pour une silhouette quotidienne.',sizes:['XS','S','M','L','XL','XXL']},
 {id:'albanie',name:'ALBANIE',country:'ALBANIA',image:'images/back-albania.jpg',number:'04',description:'Une pièce inspirée de l’héritage et des symboles albanais.',detail:'Une création qui mélange héritage culturel et langage streetwear.',sizes:['XS','S','M','L','XL','XXL']},
 {id:'algerie',name:'ALGÉRIE',country:'ALGERIA',image:'images/back-algeria-zellige.jpg',number:'05',description:'Une pièce inspirée des formes, couleurs et architectures d’Algérie.',detail:'Une présence graphique forte construite autour de références méditerranéennes.',sizes:['XS','S','M','L','XL','XXL']},
 {id:'jordanie',name:'JORDANIE',country:'JORDAN',image:'images/back-jordan.jpg',number:'06',description:'Une pièce inspirée des paysages et de la culture jordanienne.',detail:'Une esthétique minérale et intemporelle pour une pièce de caractère.',sizes:['XS','S','M','L','XL','XXL']},
 {id:'madagascar',name:'MADAGASCAR',country:'MADAGASCAR',image:'images/back-madagascar.jpg',number:'07',description:'Une pièce inspirée de l’identité unique de Madagascar.',detail:'Une pièce pensée comme un hommage aux influences et aux textures de l’île.',sizes:['XS','S','M','L','XL','XXL']},
 {id:'turquie',name:'TURQUIE',country:'TURKEY',image:'images/back-turkey.jpg',number:'08',description:'Une pièce inspirée des motifs et de l’héritage turc.',detail:'Des références historiques traduites dans une esthétique moderne.',sizes:['XS','S','M','L','XL','XXL']},
 {id:'rdc',name:'R.D. CONGO',country:'DR CONGO',image:'images/back-rdcongo.jpg',number:'09',description:'Une pièce inspirée de la culture et de l’énergie de la RDC.',detail:'Une identité forte, portée par une direction artistique contemporaine.',sizes:['XS','S','M','L','XL','XXL']},
 {id:'reunion',name:'LA RÉUNION',country:'RÉUNION',image:'images/back-reunion.jpg',number:'10',description:'Une pièce inspirée de l’île et de ses influences culturelles.',detail:'Une création solaire et métissée qui clôture le Drop 001.',sizes:['XS','S','M','L','XL','XXL']}
];
window.BANKSO_PRODUCTS.findById=id=>window.BANKSO_PRODUCTS.find(p=>p.id===id);
